### ISSUE TITLE
Expecting value: line 1 column 1 (char 0) when calling getVideo() print(video['accurate_views'])

### ISSUE THREAD

**Issue by MajorLayzor** [sskender/pornhub-api#24]
Seems like the problem is this line: 
`script_data = self._scrapScriptInfo(soup_data.find("script", type="application/ld+json").text)`
which yields an empty string. 
Why is `script_dict = json.loads(soup_data.replace("'",'"'))` needed anyway? What is replacing` "` by` ' `used for for?

Possible fix would be to use `script_dict = json.loads(script.contents[0]) `if the replace function isn´t actually needed.

**Comment by sskender** [comment]
I would be grateful if a PR could be made with the fix.

**Comment by MajorLayzor** [comment]
Can you let me know why the character replacement happens please ? Otherwise the fix might actually break things.

**Comment by sskender** [comment]
Not sure, it was not my commit.

**Comment by MajorLayzor** [comment]
Ok turns out the problem might actually be that pornhub recognises it as a bot and forwards every request to a troll site "cornhub"...
Working on a fix I think it´s the header

**Comment by MajorLayzor** [comment]
What else is being sent with the request aside from `"HEADERS"` ? Something else must look suspicious to the pornhubs bot detection
