### ISSUE TITLE
GetVideos Module Has an Error

### ISSUE THREAD

**Issue by Yeung-Ming** [sskender/pornhub-api#29]
File: Videos.py
Function: _scrapVideiosInfo(self,div_el)

The divs attribute has be changed.The images Tag was rename to "data-mediuthumb".

I change there code on my local Computer. Now I want to merge into origin code.
![微信图片_20231214112444](https://github.com/sskender/pornhub-api/assets/74055211/025a53b6-7df2-4ee4-a6d6-a600739e42df)
![微信图片_20231214112449](https://github.com/sskender/pornhub-api/assets/74055211/f32c7c2a-a9ab-454a-a62d-1b367742e455)
![微信图片_20231214112524](https://github.com/sskender/pornhub-api/assets/74055211/61c31f9a-b6a1-4141-85ed-f55a394f0f72)

**Comment by sskender** [comment]
Thank you for your PR!
