### ISSUE TITLE
Make package install-able with pip

### ISSUE THREAD

**Issue by AltGit00** [sskender/pornhub-api#5]
If possible, could you make this package install-able with pip? Would be great as this currently does not have a setup.py file and is causing issues with larger programs where this package would be placed in a requirements.txt file.

Thank you so much if you could!

**Comment by sskender** [comment]
I am sorry for such a late response.

This project is not actively maintained, I am surprised everything still works and people like it!

I will try to do that as soon as I find free time. Stay tuned :D

**Comment by Mr-Steal-Your-Script** [comment]
I can do it for you, if I can get your permission!

**Comment by sskender** [comment]
Of course, PR are more than welcome!

**Comment by Mr-Steal-Your-Script** [comment]
I've previously uploaded to PyPI, so this shouldn't be too hard. [twine](https://twine.readthedocs.io/en/latest/) makes it easy.

**Comment by sskender** [comment]
It looks like it's working as it is supposed to. Great!
I think this issue can be closed now, let me know if you agree.

**Comment by Mr-Steal-Your-Script** [comment]
agreed!
